--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pixelforge-studios-PMMP/SkyblockCore
build-by-default: true
branches:
- main
projects:
  SkyblockCore:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
    libs:
     - src: poggit/libasynql/libasynql
       version: ^4.1.6
     - src: dktapps-pm-pl/pmforms/pmforms
       version: ^2.1.0
     - src: muqsit/InvMenu/InvMenu
       branch: pm5
       version: ^4.7.3 
     - src: IvanCraft623/Pahtfinder/pathfinder
       version: ^0.0.3
       branch: main
...
